version: "3"
services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    entrypoint: sh -c "sleep 120 && node create-database.js"
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_SUPERUSER_USERNAME=root
      - CASSANDRA_SUPERUSER_PASSWORD=root